## Importing necessary modules


In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
img_src_4_points = cv2.imread("images/homography_1.jpg")
resize_parameter = 1.3
plane_size = (round(130 * resize_parameter),round(160 * resize_parameter))


## Interface to select points and input their real coordinates

In [3]:

# Define the callback function for mouse events
def mouse_callback(event, x, y, flags, params):
    # If left button is clicked, record the point coordinates
    if event == cv2.EVENT_LBUTTONDOWN:
        try:
            params['points'].append([x, y])
            cv2.circle(params['img_select_points'], (x, y), 5, (0, 0, 255), -1)
            x,y = input('Enter the real coordinates of the point in the format: x, y: ').split(',')
            params['real_coords'].append([float(x), float(y)])
        except:
            print('Invalid input')
            params['points'].pop()
            cv2.circle(params['img_select_points'], (x, y), 5, (0, 0, 0), -1)
            if len(params['real_coords']) > params['points']:
                params['real_coords'].pop()

# Create a window and set the mouse callback function
def select_points_from_image(img_src, no_of_points=4):
    img_select_points = img_src.copy()
    cv2.namedWindow('image')
    params = {'points': [], 'real_coords': [], 'img_select_points': img_select_points}
    cv2.setMouseCallback('image', mouse_callback, params)

    # Display the image and wait for user to select points
    while True:
        cv2.imshow('image', img_select_points)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        if len(params['points']) == no_of_points:
            break

    selected_pts = np.array(params['points']) 
    real_coords =  np.array(params['real_coords'])

    # Print the selected points
    print('Selected points:', selected_pts)
    print('Real coordinates:', real_coords)
    cv2.destroyAllWindows()
    return selected_pts, real_coords

pts_selected, coords_real = select_points_from_image(img_src_4_points, 4)

Selected points: [[441 199]
 [539 296]
 [370 378]
 [428 578]]
Real coordinates: [[ 20.  24.]
 [ 70.  48.]
 [ 50.  96.]
 [100. 137.]]


## Calculate homography matrix and Warp image based on it

In [4]:
def calculate_homography_and_warp(selected_pts, real_coords,img_src, plane_size, no_of_points=4):
    # Calculate Homography
    h, status = cv2.findHomography(selected_pts, real_coords)


    print('Homography Matrix:\n', h)
    # Warp source image to destination based on homography
    im_out = cv2.warpPerspective(img_src, h, plane_size)

    cv2.imwrite(f'images/warped_image_{no_of_points}_points.jpg', im_out)
    # Display images
    cv2.imshow("Source Image", img_src)
    cv2.imshow("Warped Source Image", im_out)

    cv2.waitKey(0)

    cv2.destroyAllWindows()
    return h

selected_pts = np.array(pts_selected) 
real_coords =  np.array(coords_real)
homography_matrix = calculate_homography_and_warp(selected_pts, real_coords,img_src_4_points, plane_size)

Homography Matrix:
 [[ 5.18716362e-01  5.81657973e-01 -3.09228413e+02]
 [-2.07863840e-01  7.81188723e-01 -2.14580752e+01]
 [ 8.54253329e-04  1.94495598e-03  1.00000000e+00]]


## Warp results with 4 points

### Original Image
![](./images/homography_1.jpg)

### Warped Image
![](./images/warped_image_4_points.jpg)

## Select two points on the image and calculate real distance and real coords on plane

In [5]:

def point_select_and_dist(img_select_points, h):
    
    def midpoint(p1, p2):
        return (round((p1[0]+p2[0])/2), round((p1[1]+p2[1])/2))

    def mouse_callback(event, x, y, flags, params):
        # If left button is clicked, record the point coordinates
        if event == cv2.EVENT_LBUTTONDOWN:
            point_in_image = np.array([x, y])
            params['image_coords'].append(point_in_image)
            # Convert the point to homogeneous coordinates
            point_hom = np.append(point_in_image, 1)
            # Compute the corresponding point in planar coordinates
            point_in_planar = np.dot(h, point_hom)
            point_in_planar /= point_in_planar[2] # Normalize the point  
            point_in_planar = point_in_planar[:2] # Remove the third coordinate
            params['planar_coords'].append(point_in_planar)
            cv2.circle(img_select_points, (x, y), 5, (255, 0, 0), -1)
            cv2.putText(img_select_points, str(point_in_planar), (x + 1, y + 1), cv2.FONT_HERSHEY_PLAIN, 1, (255, 0, 0), 2, cv2.LINE_AA)

    # Create a window and set the mouse callback function
    cv2.namedWindow('image')
    params = {'image_coords': [], 'planar_coords': []}
    cv2.setMouseCallback('image', mouse_callback, params)

    # Display the image and wait for user to select points
    while True:
        cv2.imshow('image', img_select_points)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        if len(params['image_coords']) == 2:
            break

    cv2.destroyWindow('image')
    # Print the selected points
    print('Point 1:', params['image_coords'][0], '->', params['planar_coords'][0])
    print('Point 2:', params['image_coords'][1], '->', params['planar_coords'][1])
    distance = np.linalg.norm(params['planar_coords'][0] - params['planar_coords'][1])
    print('Euclidean Distance between points :', distance, ' mm')

    # draw a line in between the two points
    cv2.line(img_select_points, tuple(params['image_coords'][0]), tuple(params['image_coords'][1]), (0, 255, 0), 2)
    middle_point_of_line = midpoint(params['image_coords'][0], params['image_coords'][1])
    cv2.putText(img_select_points, str(distance), middle_point_of_line, cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0), 2, cv2.LINE_8)

    cv2.imshow('image_with_dist', img_select_points)
    cv2.imwrite('images/line_with_dist_4_points.jpg', img_select_points)
    cv2.waitKey(0)

    # Close all windows
    cv2.destroyAllWindows()

img_select_points = img_src_4_points.copy()
point_select_and_dist(img_select_points,homography_matrix)

Point 1: [442 199] -> [20.88953407 24.68938929]
Point 2: [540 297] -> [70.21938193 47.86923564]
Euclidean Distance between points : 54.50448757605261  mm


# Image with distance between two points
Its quite accurate! 

![ayo](./images/line_with_dist_4_points.jpg)

## Introducing the same plane but now with 10 points

In [6]:
img_src_10_points = cv2.imread("images/homography_3.jpg")

pts_selected_10, coords_real_10 = select_points_from_image(img_src_10_points,10)


Selected points: [[429  65]
 [724 105]
 [555 151]
 [672 249]
 [507 157]
 [388 190]
 [393 238]
 [508 419]
 [239 287]
 [ 96 327]]
Real coordinates: [[ 20.  24.]
 [100.   8.]
 [ 70.  48.]
 [110.  77.]
 [ 60.  57.]
 [ 40.  80.]
 [ 50.  96.]
 [100. 137.]
 [ 30. 129.]
 [ 10. 152.]]


## Calculate homography matrix and Warp image based on it (again)

In [7]:
selected_pts_10 = np.array(pts_selected_10) 
real_coords_10 =  np.array(coords_real_10)
homography_matrix = calculate_homography_and_warp(selected_pts_10, real_coords_10,img_src_10_points, plane_size, 10)

Homography Matrix:
 [[ 2.83478608e-01  3.34965953e-01 -1.21636584e+02]
 [-1.31099593e-01  5.93000080e-01  4.34686251e+01]
 [ 3.70891185e-05  1.46104550e-03  1.00000000e+00]]


## Warp results with 10 points

### Original Image
![](./images/homography_3.jpg)

### Warped Image
![](./images/warped_image_10_points.jpg)

In [8]:
img_select_points = img_src_10_points.copy()
point_select_and_dist(img_select_points,homography_matrix)


Point 1: [238 288] -> [ 29.58958693 128.04272554]
Point 2: [ 95 328] -> [ 10.22610255 152.0949176 ]
Euclidean Distance between points : 30.878025685621836  mm


## Establish a wrong correspondence in the points and their real coordinates, without applying RANSAC


In [15]:
def calculate_homography_with_wrong_correspondence_and_warp(selected_pts, real_coords,img_src, plane_size, number_of_wrongs, use_ransac=False):
    # Calculate Homography
    # swap the points to see the effect of wrong correspondence
    selected_pts_deep_copy = selected_pts.copy()
    real_coords_deep_copy = real_coords.copy()

    for i in range(number_of_wrongs):
        selected_pts_deep_copy[i], selected_pts_deep_copy[i+1] = selected_pts_deep_copy[i+1], selected_pts_deep_copy[i]
    
    h = None
    if use_ransac:
        h, status = cv2.findHomography(selected_pts_deep_copy, real_coords_deep_copy, cv2.RANSAC, 5.0)
    else:
        h, status = cv2.findHomography(selected_pts_deep_copy, real_coords_deep_copy)


    print('Homography Matrix:\n]', h)
    # Warp source image to destination based on homography
    im_out = cv2.warpPerspective(img_src, h, plane_size)

    cv2.imwrite(f'images/warped_image_with_{number_of_wrongs + 1}_wrong_cor{"RANSAC" if use_ransac else "NO_RANSAC"}.jpg', im_out)
    # Display images
    cv2.imshow("Source Image", img_src)
    cv2.imshow("Warped Source Image", im_out)

    cv2.waitKey(0)

    cv2.destroyAllWindows()
    return h

homography_matrix = calculate_homography_with_wrong_correspondence_and_warp(selected_pts_10, real_coords_10,img_src_10_points, plane_size, 3, use_ransac=False)


Homography Matrix:
] [[-3.68627403e+01 -5.74448326e+01  2.00734791e+04]
 [-3.81351415e+00 -8.76908164e+01  8.94502331e+03]
 [-2.08747394e-01 -3.14024278e-01  1.00000000e+00]]


We get an image with a pretty silly perspective
Now, let's try to apply RANSAC.

In [14]:
homography_matrix = calculate_homography_with_wrong_correspondence_and_warp(selected_pts_10, real_coords_10,img_src_10_points, plane_size, 3, use_ransac=True)


Homography Matrix:
] [[ 3.64485217e-01  4.52391114e-01 -1.66206655e+02]
 [-1.26052381e-01  7.69879914e-01  2.69595066e+01]
 [ 2.93927380e-04  2.22074487e-03  1.00000000e+00]]


We see that RANSAC was able to detect the wrong correspondeces we introduced, and so the wrapped image produced is one with a correct frontal perspective display.

### Image with 2 wrong correspondences without RANSAC
![](./images/warped_image_with_2_wrong_corNO_RANSAC.jpg)

###  Image with 2 wrong correspondences with RANSAC
![](./images/warped_image_with_2_wrong_corRANSAC.jpg)
